import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1a1a2a",
  },
  scrollViewContent: {
    flexGrow: 1,
    paddingHorizontal: 10,
    paddingBottom: 20,
  },
  emptyStateText: {
    color: "#b0b0b0",
    textAlign: "center",
    marginTop: 50,
    fontSize: 16,
  },
  machineGroup: {
    marginBottom: 20,
  },
  groupTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#a0d911",
    marginBottom: 10,
    marginLeft: 5,
    borderBottomWidth: 1,
    borderBottomColor: "#444455",
    paddingBottom: 5,
  },
  machineCard: {
    backgroundColor: "#2a2a3a",
    borderRadius: 10,
    padding: 15,
    marginVertical: 8,
    marginHorizontal: 5,
    borderWidth: 1,
    borderColor: "#444455",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  machineInfo: {
    flex: 1,
    marginRight: 10,
  },
  machineStatus: {
    fontSize: 16,
    color: "#ffffff",
    marginVertical: 8,
  },
  machineName: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#ffffff",
    marginBottom: 5,
  },
  machineDescription: {
    fontSize: 13,
    color: "#b0b0b0",
    marginBottom: 5,
  },
  machineDetail: {
    fontSize: 14,
    color: "#e0e0e0",
    marginBottom: 2,
  },
  upgradeButton: {
    backgroundColor: "#007bff",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 5,
  },
  upgradeButtonText: {
    color: "#ffffff",
    fontWeight: "bold",
    fontSize: 14,
  },
  /* Node selector styles */
  nodeSelectorModal: {
    backgroundColor: '#23243aff',
    borderRadius: 14,
    padding: 14,
    zIndex: 120,
    elevation: 22,
    shadowColor: '#000',
    shadowOpacity: 0.45,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    marginHorizontal: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  modalTitle: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    textAlign: 'center',
    flex: 1,
    marginLeft: 8,
  },
  closeButton: { padding: 6 },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2c2c44',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 10,
    gap: 8,
  },
  searchInput: { flex: 1, color: '#fff', fontSize: 14 },
  tabContainer: { marginBottom: 10 },
  resourceTab: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2c2c44',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    gap: 8,
  },
  activeTab: { backgroundColor: '#4CAF50' },
  tabText: { color: '#bbb', fontSize: 13, fontWeight: '600' },
  activeTabText: { color: '#fff' },
  nodeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2c2c44',
    borderRadius: 10,
    padding: 12,
    marginVertical: 6,
    borderWidth: 1,
    borderColor: '#444',
  },
  nodeIconContainer: { marginRight: 10 },
  nodeInfo: { flex: 1 },
  nodeName: { color: '#fff', fontSize: 15, fontWeight: '700', marginBottom: 2 },
  nodeLocation: { color: '#bbb', fontSize: 12, marginBottom: 6 },
  nodeProgress: { height: 4 },
  nodeStats: { alignItems: 'flex-end', gap: 6 },
  nodeCapacity: { color: '#4CAF50', fontWeight: '700', fontSize: 13 },
  emptyText: { color: '#bdbdbd', fontSize: 14, textAlign: 'center', marginVertical: 18, fontStyle: 'italic' },
});

export default styles;
