import { StyleSheet, Dimensions } from "react-native";
import Colors from "../../constants/Colors";

const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  backgroundImage: {
    position: 'absolute',
    width: width,
    height: height,
    resizeMode: 'cover',
  },
  container: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)', // Darker semi-transparent overlay
  },
  header: {
    backgroundColor: "#2c2c2c",
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 2,
    borderBottomColor: "#ff9800",
    shadowColor: "#ff9800",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#e8f4fd",
    textAlign: "center",
    textShadowColor: "#ff9800",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },

  // Tab navigation styles
  tabContainer: {
    flexDirection: "row",
    backgroundColor: "rgba(44, 44, 44, 0.75)",
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(68, 68, 68, 0.6)",
    backdropFilter: "blur(10px)",
  },
  tabButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginHorizontal: 4,
    borderRadius: 8,
    backgroundColor: "rgba(58, 58, 58, 0.7)",
    borderWidth: 1,
    borderColor: "rgba(85, 85, 85, 0.8)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  activeTabButton: {
    backgroundColor: "rgba(255, 152, 0, 0.85)",
    borderColor: "rgba(255, 152, 0, 0.9)",
    shadowColor: "#ff9800",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
    elevation: 5,
  },
  tabButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#b8c7d1",
    marginLeft: 6,
  },
  activeTabButtonText: {
    color: "#e8f4fd",
    textShadowColor: "rgba(0,0,0,0.3)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },

  // Content container
  contentContainer: {
    flex: 1,
  },

  // Recipe tab styles
  recipeTab: {
    flex: 1,
    backgroundColor: "transparent",
  },
  panelHeader: {
    backgroundColor: "rgba(44, 44, 44, 0.75)",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(68, 68, 68, 0.6)",
    backdropFilter: "blur(8px)",
  },
  panelTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#e8f4fd",
    textShadowColor: "rgba(0, 0, 0, 0.5)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  recipeList: {
    flex: 1,
    backgroundColor: "transparent",
  },
  recipeListContent: {
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  recipeCard: {
    backgroundColor: "rgba(44, 44, 44, 0.75)",
    marginVertical: 6,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(68, 68, 68, 0.8)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
    backdropFilter: "blur(12px)",
  },
  selectedRecipeCard: {
    backgroundColor: "rgba(58, 58, 58, 0.85)",
    borderColor: "rgba(255, 152, 0, 0.9)",
    borderWidth: 2,
    shadowColor: "#ff9800",
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 5,
  },
  recipeCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  recipeIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 0,
    backgroundColor: "rgba(50, 50, 50, 0.7)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
    padding: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 1,
  },
  recipeIcon: {
    width: 28,
    height: 28,
    resizeMode: 'contain',
  },
  recipeInfo: {
    flex: 1,
  },
  recipeCardTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#e8f4fd",
    marginBottom: 4,
  },
  selectedRecipeCardTitle: {
    color: "#e8f4fd",
    textShadowColor: "#ff9800",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  recipeCardTime: {
    fontSize: 12,
    color: "#b8c7d1",
  },
  recipeDetails: {
    marginTop: 8,
  },
  recipeInputsOutputs: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  recipeInputs: {
    flex: 1,
  },
  recipeOutputs: {
    flex: 1,
    alignItems: "flex-end",
  },
  recipeDetailLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#ff9800",
    marginBottom: 4,
    flexDirection: "row",
    alignItems: "center",
  },
  recipeDetailText: {
    fontSize: 11,
    color: "#b8c7d1",
    marginBottom: 2,
  },
  recipeResourceItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 2,
  },
  recipeResourceIcon: {
    width: 16,
    height: 16,
    marginRight: 4,
    resizeMode: 'contain',
  },
  arrowIcon: {
    marginHorizontal: 12,
  },

  // Production tab styles
  productionTab: {
    flex: 1,
    backgroundColor: "transparent",
  },
  productionMainArea: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },

  // Flow section styles
  flowSection: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(44, 44, 44, 0.75)",
    padding: 16,
    marginVertical: 12,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "rgba(255, 152, 0, 0.8)",
    shadowColor: "#ff9800",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 5,
    backdropFilter: "blur(10px)",
  },
  inputSection: {
    flex: 1,
    alignItems: "center",
  },
  outputSection: {
    flex: 1,
    alignItems: "center",
  },
  arrowSection: {
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  flowLabel: {
    backgroundColor: "#444",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#ff9800",
  },
  flowLabelText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#ff9800",
    letterSpacing: 1,
  },
  inputSlots: {
    alignItems: "center",
  },
  outputSlots: {
    alignItems: "center",
  },
  resourceSlot: {
    alignItems: "center",
    marginVertical: 8,
    padding: 12,
    backgroundColor: "rgba(50, 50, 50, 0.75)",
    borderRadius: 0,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
    minWidth: 100,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 2,
    backdropFilter: "blur(8px)",
  },
  slotIcon: {
    width: 48,
    height: 48,
    borderRadius: 0,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 1,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
    backgroundColor: "rgba(50, 50, 50, 0.7)",
  },
  slotIconImage: {
    width: 32,
    height: 32,
    resizeMode: 'contain',
  },
  slotInfoContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  slotInfoIcon: {
    marginRight: 4,
  },
  slotAmount: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#e8f4fd",
    marginBottom: 4,
  },
  slotName: {
    fontSize: 12,
    color: "#b8c7d1",
    textAlign: "center",
    marginBottom: 4,
  },
  slotInventory: {
    fontSize: 11,
    textAlign: "center",
    color: Colors.textMuted,
  },

  // Machine status section
  machineStatusSection: {
    marginVertical: 16,
  },
  machineInfoCard: {
    backgroundColor: "rgba(44, 44, 44, 0.75)",
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: "rgba(68, 68, 68, 0.8)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
    backdropFilter: "blur(15px)",
  },
  machineHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  machineIcon: {
    width: 50,
    height: 50,
    borderRadius: 0,
    backgroundColor: "rgba(50, 50, 50, 0.7)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
    padding: 5,
  },
  machineIconImage: {
    width: 36,
    height: 36,
    resizeMode: 'contain',
  },
  machineInfo: {
    flex: 1,
  },
  machineTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#e8f4fd",
    marginBottom: 2,
  },
  recipeTitle: {
    fontSize: 14,
    color: "#ff9800",
    fontWeight: "500",
  },
  machineStatus: {
    flexDirection: "row",
    alignItems: "center",
  },
  statusIndicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 8,
  },
  statusText: {
    fontSize: 12,
    color: "#b8c7d1",
    fontWeight: "500",
  },
  productionStats: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#444",
  },
  statItem: {
    alignItems: "center",
  },
  statLabel: {
    fontSize: 11,
    color: "#b8c7d1",
    marginBottom: 4,
    flexDirection: "row",
    alignItems: "center",
  },
  statIcon: {
    marginRight: 4,
  },
  statValue: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#ff9800",
  },

  // Progress section
  progressSection: {
    marginVertical: 12,
  },

  // Controls section
  controlsSection: {
    marginTop: 20,
    marginBottom: 40,
  },
  quantityControls: {
    backgroundColor: "rgba(44, 44, 44, 0.75)",
    borderRadius: 12,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(68, 68, 68, 0.8)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
    backdropFilter: "blur(12px)",
  },
  controlLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#e8f4fd",
    marginBottom: 16,
    textAlign: "center",
  },
  quantityStepperContainer: {
    marginBottom: 20,
    backgroundColor: "rgba(58, 58, 58, 0.85)",
    borderRadius: 8,
    padding: 10,
    borderWidth: 1,
    borderColor: "rgba(85, 85, 85, 0.8)",
  },
  quantityInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
    backgroundColor: "#3a3a3a",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#555",
  },
  quantityLabel: {
    fontSize: 14,
    color: "#b8c7d1",
    marginRight: 12,
  },
  quantityValue: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#ff9800",
    minWidth: 40,
    textAlign: "center",
  },
  quickButtons: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  CraftPanel: {
    marginTop: 12,
    alignItems: "center",
  },
  startProductionButton: {
    backgroundColor: "rgba(255, 152, 0, 0.85)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 152, 0, 0.9)",
    shadowColor: "#ff9800",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 7,
    backdropFilter: "blur(8px)",
  },
  startProductionButtonDisabled: {
    backgroundColor: "rgba(68, 68, 68, 0.6)",
    borderColor: "rgba(85, 85, 85, 0.4)",
    shadowOpacity: 0,
    elevation: 0,
  },
  startProductionButtonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#e8f4fd",
    marginLeft: 8,
    textShadowColor: "rgba(0,0,0,0.3)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  startProductionButtonTextDisabled: {
    color: "#6b7885",
    textShadowOpacity: 0,
  },
});
