import { StyleSheet } from "react-native";
import Colors from "../../../../constants/Colors";

const styles = StyleSheet.create({
  machineCard: {
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 12,
    marginBottom: 12,
    padding: 0,
    position: "relative",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 4,
    width: "100%",
    minHeight: 140,
    overflow: "hidden",
  },
  lockedMachineCard: {
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    borderColor: "rgba(255, 255, 255, 0.1)",
    opacity: 0.8,
  },
  availableMachineCard: {
    borderColor: "#00ffff",
    borderWidth: 2,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    shadowColor: "#00ffff",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 6,
  },
  cardContent: {
    flexDirection: "row",
    padding: 12,
    gap: 12,
  },
  leftSection: {
    alignItems: "center",
    justifyContent: "center",
    width: 100,
  },
  rightSection: {
    flex: 1,
    justifyContent: "space-between",
  },
  statusBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: Colors.textDanger,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    zIndex: 1,
    shadowColor: Colors.textDanger,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 3,
  },
  statusBadgeText: {
    color: Colors.textPrimary,
    fontSize: 9,
    fontWeight: "800",
    marginLeft: 2,
    letterSpacing: 0.5,
  },
  machineIconLarge: {
    width: 70,
    height: 70,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 255, 255, 0.1)",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "rgba(0, 255, 255, 0.3)",
    marginBottom: 8,
  },
  machineName: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 12,
    letterSpacing: 0.3,
    lineHeight: 14,
    textAlign: "center",
    textShadowColor: "rgba(0, 0, 0, 0.5)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  lockedMachineName: {
    color: Colors.textMuted,
  },
  requirementsContainer: {
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    borderRadius: 8,
    padding: 4,
    marginBottom: 8,
    borderWidth: 1,
    flex: 1,
  },
  requirementsList: {},
  requirementItem: {
    flexDirection: "column",
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginBottom: 4,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    gap: 4,
  },
  requirementItemMissing: {
    borderColor: "rgba(239, 83, 80, 0.3)",
    backgroundColor: "rgba(239, 83, 80, 0.05)",
  },
  requirementHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  requirementText: {
    flex: 1,
    color: "rgba(255, 255, 255, 0.9)",
    fontSize: 13,
    fontWeight: "600",
  },
  requirementAmounts: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 28,
  },
  requirementAmountBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    minWidth: 50,
    alignItems: "center",
    borderWidth: 1,
  },
  requirementAmountText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#fff",
  },
  hasEnoughAmount: {
    backgroundColor: "rgba(76, 175, 80, 0.3)",
    borderColor: "#4CAF50",
  },
  needsAmount: {
    backgroundColor: "rgba(239, 83, 80, 0.3)",
    borderColor: "#EF5350",
  },
  noRequirementsContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 4,
    paddingHorizontal: 6,
    backgroundColor: Colors.accentGreen + "20",
    borderRadius: 6,
    borderWidth: 1,
    borderColor: Colors.accentGreen,
  },
  noRequirementsText: {
    color: Colors.accentGreen,
    fontSize: 10,
    fontWeight: "600",
    marginLeft: 4,
    textAlign: "center",
  },
  buildButtonGradient: {
    borderRadius: 10,
    padding: 2,
  },
  buildButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.2)",
    minHeight: 36,
  },
  buildingButton: {
    opacity: 0.95,
    transform: [{ translateY: -1 }],
  },
  buildingOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  buildingText: {
    color: Colors.textPrimary,
    fontSize: 11,
    fontWeight: "800",
    backgroundColor: "transparent",
  },
  availableBuildButton: {
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    borderWidth: 0,
  },
  lockedBuildButton: {
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    borderColor: "rgba(255, 255, 255, 0.15)",
    shadowOpacity: 0.1,
    elevation: 1,
  },
  disabledBuildButton: {
    backgroundColor: "rgba(239, 83, 80, 0.2)",
    borderColor: "#EF5350",
  },
  buildButtonText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
    marginLeft: 6,
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
});

export default styles;
