// screens/InventoryScreen/styles.js
import { StyleSheet } from "react-native";
import Colors from "../../constants/Colors";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  backgroundImageContainer: {
    flex: 1,
  },
  gradientOverlay: {
    flex: 1,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: '#00ffff',
    textAlign: "center",
    paddingVertical: 20,
    marginTop: 10,
    textShadowColor: 'rgba(0, 255, 255, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  scrollViewContent: {
    flexGrow: 1,
    paddingHorizontal: 10,
    paddingBottom: 100,
  },
  inventoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
  },
  gridItem: {
    width: "30%",
    aspectRatio: 1,
    margin: "1.66%",
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: 'rgba(0, 255, 255, 0.4)',
    alignItems: "center",
    justifyContent: "center",
    padding: 5,
    position: "relative",
    shadowColor: '#00ffff',
    shadowOpacity: 0.3,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 0 },
    elevation: 3,
  },
  iconContainer: {
    width: "70%",
    height: "70%",
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 255, 0.3)',
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  itemIcon: {
    width: '90%',
    height: '90%',
  },
  iconText: {
    color: '#00ffff',
    fontSize: 28,
    fontWeight: "bold",
    textShadowColor: 'rgba(0, 255, 255, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  itemName: {
    fontSize: 11,
    color: '#ffffff',
    marginTop: 5,
    textAlign: "center",
    position: "absolute",
    bottom: 20,
    width: "100%",
    fontWeight: '600',
  },
  amountOverlay: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: 'rgba(255, 0, 204, 0.8)',
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 2,
    minWidth: 25,
    alignItems: "center",
    justifyContent: "center",
    borderTopLeftRadius: 0,
    borderTopRightRadius: 8,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 8,
  },
  itemAmount: {
    fontSize: 12,
    fontWeight: "bold",
    color: '#ffffff',
  },
  emptyInventoryText: {
    color: 'rgba(255, 255, 255, 0.7)',
    textAlign: "center",
    marginTop: 50,
    fontSize: 16,
    paddingHorizontal: 20,
  },
});

export default styles;
